param(
    [switch] $SkipBuild
)

$ErrorActionPreference = "Stop"
$probe = Join-Path $PSScriptRoot "baremetal-qemu-allocator-syscall-probe-check.ps1"

function Extract-IntValue {
    param([string] $Text, [string] $Name)
    $match = [regex]::Match($Text, '(?m)^' + [regex]::Escape($Name) + '=(-?\d+)\r?$')
    if (-not $match.Success) { return $null }
    return [int64]::Parse($match.Groups[1].Value)
}

$probeOutput = if ($SkipBuild) { & $probe -SkipBuild 2>&1 } else { & $probe 2>&1 }
$probeExitCode = $LASTEXITCODE
$probeText = ($probeOutput | Out-String)
$probeOutput | Write-Output
if ($probeText -match '(?m)^BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE=skipped\r?$') {
    Write-Output 'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_FINAL_RESET_STATE_PROBE=skipped'
    exit 0
}
if ($probeExitCode -ne 0) {
    throw "Underlying allocator-syscall probe failed with exit code $probeExitCode"
}

$names = @(
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_OPS_BEFORE_RESET',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_FREE_OPS_BEFORE_RESET',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_PEAK_BYTES_BEFORE_RESET',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_DISPATCH_COUNT_BEFORE_RESET',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_ID_BEFORE_RESET',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_HEAP_BASE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_PAGE_SIZE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_FREE_PAGES',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOCATION_COUNT',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_OPS',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_FREE_OPS',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_BYTES_IN_USE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_PEAK_BYTES_IN_USE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_ALLOC_PTR',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_ALLOC_SIZE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_FREE_PTR',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_FREE_SIZE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_BITMAP0',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_BITMAP1',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_RECORD0_STATE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_RECORD0_PTR',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_RECORD0_PAGE_LEN',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENABLED',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY_COUNT',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_ID',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_DISPATCH_COUNT',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_INVOKE_TICK',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_RESULT',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_STATE',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_FLAGS',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_TOKEN',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_INVOKE_COUNT',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_LAST_ARG',
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_LAST_RESULT'
)
$values = @{}
foreach ($name in $names) {
    $values[$name] = Extract-IntValue -Text $probeText -Name $name
    if ($null -eq $values[$name]) { throw "Missing final reset field $name" }
}
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_OPS_BEFORE_RESET'] -ne 1) { throw 'Expected ALLOC_OPS_BEFORE_RESET=1.' }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_FREE_OPS_BEFORE_RESET'] -ne 1) { throw 'Expected FREE_OPS_BEFORE_RESET=1.' }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_PEAK_BYTES_BEFORE_RESET'] -ne 8192) { throw 'Expected PEAK_BYTES_BEFORE_RESET=8192.' }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_DISPATCH_COUNT_BEFORE_RESET'] -ne 2) { throw 'Expected SYSCALL_DISPATCH_COUNT_BEFORE_RESET=2.' }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_ID_BEFORE_RESET'] -ne 7) { throw 'Expected SYSCALL_LAST_ID_BEFORE_RESET=7.' }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_HEAP_BASE'] -ne 1048576) { throw 'Expected HEAP_BASE=1048576.' }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_PAGE_SIZE'] -ne 4096) { throw 'Expected PAGE_SIZE=4096.' }
$zeroNames = @(
  'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOCATION_COUNT','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_OPS','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_FREE_OPS','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_BYTES_IN_USE','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_PEAK_BYTES_IN_USE','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_ALLOC_PTR','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_ALLOC_SIZE','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_FREE_PTR','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_LAST_FREE_SIZE','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_BITMAP0','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_BITMAP1','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_RECORD0_STATE','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_RECORD0_PTR','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_ALLOC_RECORD0_PAGE_LEN','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY_COUNT','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_ID','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_DISPATCH_COUNT','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_INVOKE_TICK','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_LAST_RESULT','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_STATE','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_FLAGS','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_TOKEN','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_INVOKE_COUNT','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_LAST_ARG','BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY0_LAST_RESULT'
)
foreach ($name in $zeroNames) { if ($values[$name] -ne 0) { throw "Expected $name=0. got $($values[$name])" } }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_FREE_PAGES'] -ne 256) { throw 'Expected FREE_PAGES=256.' }
if ($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENABLED'] -ne 1) { throw 'Expected SYSCALL_ENABLED=1.' }
Write-Output 'BAREMETAL_QEMU_ALLOCATOR_SYSCALL_FINAL_RESET_STATE_PROBE=pass'
Write-Output "FREE_PAGES=$($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_FREE_PAGES'])"
Write-Output "SYSCALL_ENABLED=$($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENABLED'])"
Write-Output "SYSCALL_ENTRY_COUNT=$($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_ENTRY_COUNT'])"
Write-Output "SYSCALL_DISPATCH_COUNT=$($values['BAREMETAL_QEMU_ALLOCATOR_SYSCALL_PROBE_SYSCALL_DISPATCH_COUNT'])"
